volumes:
    bored-games:
        external: true
    # other volumes...
services:
    mongo:
        image: mongo:5
        volumes:
            - bored-games:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
    # other services, too...
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
        environment:
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: bored-games
            WAIT_HOSTS: mongo:27017
            SIGNING_KEY: 874849f2621abafb2d4d57f5be921a4224147bfd96115d7ddbe849rsds80f21f5e7d0pb3d148acbc32a55hj26p3d7f4b9p00d1249e1ec892baf73572353666a97e
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_API_HOST: http://localhost:8000